### ISSUE TITLE
关于课程表导出的建议

### ISSUE THREAD

**Issue by fgsdfges** [HITSchedule/HITSchedule#19]
可不可以增加课程表导出操作，导出成***ICS***格式，就像[WakeUp课程表](https://github.com/YZune/WakeupSchedule_Kotlin)一样,这样在Outlook日历上就不用一个个添加课程了。

**Comment by leylee** [comment]
好的，这个功能在做了，预计期末考试后上线，也欢迎pr，谢谢反馈

**Comment by leylee** [comment]
已经添加此功能
