### ISSUE TITLE
“系统正在更新中”期间刷新课表得到一个空的课表

### ISSUE THREAD

**Issue by CainXCain** [HITSchedule/HITSchedule#31]
11.12在1.4.2版本更新期间刷新课表，结果是只剩下自己添加的日程，教务处课程全没了，能否处理下这个问题，要么支持在更新期间正常刷新课表，要么干脆把更新期间刷新课表暂时关闭

**Comment by leylee** [comment]
课表被清空是因为1.4.1版本使用的API接口已过时，无法获取到课表。所有使用1.4.1的用户都会遇到此问题，而与1.4.2的更新无关。1.4.2版本紧急修复了接口的错误。
