### ISSUE TITLE
课程表获取不完全，仅显示部分课程

### ISSUE THREAD

**Issue by myWillison** [HITSchedule/HITSchedule#36]
更新课程表后只有部分课程，有很多课没有显示出来，是不是因为那些课是我后来补选的？在选课系统-个人课程表里显示的是完整的。请问目前课程表数据源是从哪里获取的？

**Comment by leylee** [comment]
目前的课程表数据通过 哈尔滨工业大学微信公众号 -> 服务大厅 -> 本科生课表 获取, 更新可能存在一定延迟
