### ISSUE TITLE
验证码总是验证失败，已经无法获取课表

### ISSUE THREAD

**Issue by Terriaknight** [HITSchedule/HITSchedule#39]

**Comment by billchenchina** [comment]
本科生教务系统改成 RSA 加密了，需要做一下修改。

![image](https://user-images.githubusercontent.com/7758042/140486928-d761b1ef-7f64-42cd-8171-56bc5f014ad7.png)

https://github.com/HITSchedule/HITSchedule/blob/master/app/src/main/java/com/example/hitschedule/util/XywHttpUtil.java#L124

**Comment by csyxwei** [comment]
有相关的代码实现可以借鉴吗，不是特别麻烦的话，我可以帮着修改一下

> 本科生教务系统改成 RSA 加密了，需要做一下修改。
> 
> ![image](https://user-images.githubusercontent.com/7758042/140486928-d761b1ef-7f64-42cd-8171-56bc5f014ad7.png)
> 
> https://github.com/HITSchedule/HITSchedule/blob/master/app/src/main/java/com/example/hitschedule/util/XywHttpUtil.java#L124
