### ISSUE TITLE
能否支持VPN登录

### ISSUE THREAD

**Issue by The-last-pieces** [HITSchedule/HITSchedule#45]

**Comment by leylee** [comment]
目前最新的 1.5.2 版本支持应用内通过 VPN 获取课表. 请详细说明需求?

**Comment by The-last-pieces** [comment]
![Screenshot_20220901_152005](https://user-images.githubusercontent.com/57497990/187855784-fe857524-c45e-4d65-909e-7c4681e2d71e.jpg)

最初的登录界面的接口仍然是 ：
https://ids.hit.edu.cn/authserver/logout?service=https%3A%2F%2Fids.hit.edu.cn%2Fauthserver%2Flogin
，无法从校外登录

**Comment by leylee** [comment]
无法复现问题。ids.hit.edu.cn 可以从校外访问，建议检查网络设置。确认已关闭代理，尝试使用手机流量访问。

**Comment by The-last-pieces** [comment]
已解决 , 的确是代理的问题
