### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by 1170300323** [HITSchedule/HITSchedule#6]
感谢学长开发schedule软件，这对我们工大学生起到了很大帮助
在使用过程中我遇到了一个小问题，在这里做一个简单的反馈：
在刷新课表的时候，会输入验证码，但有的时候会多次弹出验证码的输入，并且在输入最后一次验证码确认的时候没有反应，而此时课表并没有得到刷新。
 但这个问题对schedule的使用没有影响，因为schedule在学期开始一段时间后会自动对课表进行更新，所以以上只是一个小的bug。

**Comment by Yuxiang-Wei** [comment]
我这边没有复现成功这个bug，是在课表为空时会出现这个问题吗？可以试试v1.2.6看是否还有这个问题。
