### ISSUE TITLE
A tiny problem about refreshing

### ISSUE THREAD

**Issue by 1173300917** [HITSchedule/HITSchedule#7]
BUG  report
Summary : A tiny problem while refreshing this schedule.
Product : HIT                  reporter : hit-1173300917
Reporter Email : 1173300917@stu.hit.edu.cn
Severity : normal
Version : v1.2.4
Hardware : mobile
OS : Android

Description:

When refreshing the timetable, the validation code will be input, but sometimes the input of the validation code will be popped up many times, and there is no response when the last validation code is input, while the timetable has not been refreshed.

![image](https://user-images.githubusercontent.com/48014473/60699338-fe443500-9f25-11e9-97c0-e88bc2905c93.png)

**Comment by Yuxiang-Wei** [comment]
Sorry, I haven't reproduce this bug successfully, and my version is v1.2.6, maybe you can try v1.2.6 for that.
